### ISSUE TITLE
Bitrise integration

### ISSUE THREAD

**Issue by godrei** [kawaiseb/bitrise-step-wetransfer-upload#4]
Please do not change the current working directory in a step unless it is necessary (and in this case restore the previous value once the step finished: `cd -`).
If you change the workdir further steps using relative path as input will may fail.

I think in your case you do not need to change the workdir:

- i do not see any npm package descriptor file (packages.json), so i think no npm install is needed in the step.sh
- the step.js can be called as: `$THIS_SCRIPT_DIR/upload.js "${WTU_DEBUG_MODE}" "${WTU_MAILSENDER}" "${WTU_MAILRECEIVER}" "${WTU_FILEPATH}" "${WTU_MESSAGE}" "${WTU_LANGUAGE}"`
- to install wetransfert simple use: `npm install -g wetransfert`, this will install wetransfert globally

To pass inputs to upload.js use the  lower case snake case style input IDs, like:

`$THIS_SCRIPT_DIR/upload.js "${debug_mode}" "${mail_sender}" "${mail_receiver}" "${path}" "${message}" "${language}"`

**Comment by kawaiseb** [comment]
Ok thanks Krisztián. I'm sending a new PR.

**Comment by kawaiseb** [comment]
Hi @godrei, i create a new PR, how to rewrite an existing PR ? Just to conserve history ?

**Comment by godrei** [comment]
Hi @kawaiseb , do you mean a new steplib pr? if you want to share the new version of the step, just drop the existing steplib pr and create a new one.
